### ISSUE TITLE
Repaint when html has a 'modal' dialog.

### ISSUE THREAD

**Issue by 564398053** [Biohazard90/ppapi-window-stream#1]
@Biohazard90 
When html has a bootstrap modal dialog or animation over **HWND**.  The native **HWND** paint again and again,  modal dialog or animation  covered by **HWND**, and html looks corruptted and ugly.   
Do you have any good idea to solve this problem?  :D

**Comment by Biohazard90** [comment]
With this plugin that shouldn't happen because the HWND doesn't need to be a child of the HTML window, or what do you mean exactly?

Basically I made this plugin to avoid the problem you describe.

**Comment by 564398053** [comment]
Thank you for your apply.
What I mean is the **embed element**
 `<embed id="plugin" type="application/x-ppapi-window-stream" width="500px" height="500px" />`
paint again and again, and in your code is about 45 times per second. Thus, when modal dialog or animation over the area of this **embed element**. We want to see the dialog or animation, but the dialog or animation disappeared as the element repainted．

This is what I want.
![20170811204902](https://user-images.githubusercontent.com/11308289/29250031-b9b687ae-806d-11e7-93da-754af05b2585.png)

This is the problem .
![20170811204554](https://user-images.githubusercontent.com/11308289/29250048-16db8e5c-806e-11e7-834f-2e4ae2c2966f.png)

@Biohazard90 I also tried to change the z-order of the embed element to a small value as -1, but it's doesn't work.

**Comment by Biohazard90** [comment]
Hm yes, but I have the same use case in my program:

![4627624](https://user-images.githubusercontent.com/5513441/29251033-1e0cbc5c-804e-11e7-87b4-f763ed91bf44.png)

But there is no flickering when it repaints, it still animates behind the modal.

Where did you place the source HWND? Is it a child of the web browser HWNDs? My source HWND is always behind the web browser HWND and not a child (this isn't in the plugin, it is in the window proc of the HWND).

**Comment by 564398053** [comment]
Hmm,  in your use case,  this way really works fine.  Seems that I using it in a wrong way. I will check my code to find any problem. You reply maybe the key point to solve my problem. 

That really helps me, Thanks a lot.  :D

**Comment by 564398053** [comment]
Hmm. seems has problem in `window_stream.cc` 

in this function
```
	void ReadBackBufferFromSharedMemory(pp::ImageData &image, int w, int h)
	{
		if (!CanStream())
		{
			PaintError(image, "Stream memory not initializable.");
			return;
		}
		
		unsigned short *data = (unsigned short*)CreateSharedMemory(w, h);
		
		if (data == nullptr)
		{
			PaintError(image, "Failed creating shared memory for stream.");
		}
		else
		{
			// incoming data
			int wSrc = data[0];
			int hSrc = data[1];

                       if (wSrc == w && hSrc == h)
			{
				data += 4;
				memcpy(image.data(), data, w * h * 4);
				
				//unsigned char c = *(((unsigned char*)data));
				//unsigned char c1 = *(((unsigned char*)data) + 1);
				//unsigned char c2 = *(((unsigned char*)data) + 2);
				//unsigned char c3 = *(((unsigned char*)data) + 3);
				//stringstream s;
				//s << "Yo, first byte: " << to_string(c) << ", " << to_string(c1) << ", " << to_string(c2) << ", " << to_string(c3);
				//PaintError(image, s.str(), false);
				//PaintError(image, "Streaming from memory.", false);
			}
			else
			{
				PaintError(image, "Stream size mismatching (try resizing the window).");
			}
               }
}
```
![1](https://user-images.githubusercontent.com/11308289/29299779-d75fcbf8-81a3-11e7-94cc-3d98b886d722.png)
I tried but the **wSrc** & **hSrc** is forever  zero. 

I got ppapi examples in [ppapi example](https://chromium.googlesource.com/chromium/src/ppapi/+/master/examples/) but no idea how to capture the HWND.

I found the hardest thing is to capture the HWND as image correctly. How you achieved that?  Is the uploaded `window_stream.cc` incomplete yet?

@Biohazard90 :D

**Comment by Biohazard90** [comment]
I think I am setting these directly in the source application.

The current version I uploaded here uses a memory stream, the source app is responsible for filling it. The width and height there is to verify that both the element in Chromium and the source rectangle have the same size.

If you check the commits here, there are older versions that use the HWND directly with various methods. But for me it was better to let the source application write the image to memory, because I have full control over it (copying from Dx11 backbuffer).

**Comment by 564398053** [comment]
Yeah.
For some reasons in my project the HWND not paint correctly when it's behide another window, thus the captured image corrupted. I will try to find how to resolve that problem.
What you do is brilliant. That the same way as the OpenOffice online does.

Thanks.
